config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'homes#top'

  # get 'users' => 'users#index'
  # get "users/:id/edit" => 'users#edit', as:'edit_user'
  # get 'users/:id' => 'users#show', as:'user'
  
  resources :users
  resources :books
  


  get'home/about'=>'homes#about'
  



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image       
  
  validates :name,
    length: { minimum: 2, maximum: 20 }, uniqueness: true
  
  validates :introduction,
  length: { maximum: 50 }

         

  has_many :books, dependent: :destroy
  

  def get_profile_image(width,height)
    unless self.profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    self.profile_image.variant(resize_to_limit: [100, 100]).processed
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :correct_user, only: [:edit, :update]
    
  def new
  end
  
  def index
    @book = Book.new
    @books=Book.all
    @users=current_user
  end
  
  def show
    @book = Book.new
    @user=current_user
    @books=Book.find(params[:id])
    @users=@books.user
  end 
  
  def edit
    @book=Book.find(params[:id])
    
  end 
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  

  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
    @book.save
    @users=current_user
    @books=Book.all

    # 　フラッシュ
    if Book.new(book_params)
      flash[:success] = "You have created book successfully."
    else
      flash.now[:danger] = "error"
      render :index
    end
    
    # バリテーション
    if @book.save
      redirect_to book_path(@book.id)
    else
      render :index
    end 

  end

    
  
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)

    # 　フラッシュ
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      flash.now[:danger] = "error"
      render :edit
    end

  end
  
  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:update]
  before_action :authenticate_user!

  def show
    @users=User.find(params[:id])
    @books=@users.books
    @book=Book.new
  end

  def edit
    @user=User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end 
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @books=@user.books
    # 　フラッシュ
    if @user.update(user_params)
      flash[:success] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = "error"
      render :edit
    end

    
  end


  def index
    @book = Book.new
    @user=User.all
    @users=current_user
  end
  

  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)  
  end
  
  

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user

  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
            <!--ここから-->
            
            <div class="col-md-3">
                <h2>User info</h2>
                
                <table class="table">
                    <tbody>
                        
                        <tr>
                            <%= image_tag users.get_profile_image(100,100) %>
                        </tr>
                        
                        <tr>
                            <th>name</th>
                            <th><%= users.name %></th>
                        </tr>
                        <tr>
                            <th>introduction</th>
                            <th><%= users.introduction %></th>
                        </tr>
                        
                    </tbody>
                </table>
                <div class="row">
                    <%= link_to edit_user_path(@users), class:"btn btn-outline-secondary btn-block" do%>
                        <i class="fas fa-user-cog"></i>
                       
                    <% end %>
                    
                </div>
                
                <h3>New book</h3>
                
                <!-- form_with部分 -->
                <%= form_with model: book do |f| %>
                  <p>Title</p>
                  <%= f.text_field :title  %>
                	
                  <p>Opinion</p>
                  <%= f.text_area :body %>
                    <br>
                  <%= f.submit 'Create Book' %>
                <% end %>
            </div>
            <!--ここまで-->

app/views/books/edit.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
                <h1>Editing Book</h1>
                
                <%= form_with model: @book do |f| %>
                
                    <div class="form-group">
                        <label for="book_title">Title</label><br>
                        <%= f.text_field :title , autofocus: true, id:"title" %>
                    </div>
                    
                    <div class="form-group">
                      <label for="book_body">Opinion</label><br>
                      <%= f.text_area :body, autofocus: true, id:"body" %>
                    </div>
                    
                     <%= f.submit 'Update Book' %>
                <% end %>
                <%= link_to 'Show', book_path(@book) %>
                |
                <%= link_to 'Back', books_path %>
            </div>
        </div>
    </div>
</main>

app/views/books/index.html.erb
<main>
    <p id="notice"></p>
    
    <div class="container px-5 px-sm-0" >
        
        <div class="row">
            <% if @book.errors.any? %>
              <%= @book.errors.count %>件のエラーが発生しました
              <br>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
        </div>
        
        <div class="row" >
            
            <%= render 'books/userinfo',users:@users,book:@book,books:@books %>

            <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                    
                    
                    <tbody>
                        <% @books.each do |book| %>
                        <!--@books=Book.all-->
                        <tr>
                            <td>
                                <%= link_to user_path(book.user.id) do %>   
                                    <%= image_tag book.user.get_profile_image(100,100) %>
                                <% end %> 
                            </td>
                            
                            <td>
                            　<%= link_to book_path(book.id) do %>   
                                <%= book.title %>
                              <% end %> 
                            </td>
                            
                            <td><%= book.body %></td>
                            
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                
            </div>
        </div>
    </div>
    </div>
</main>

app/views/books/show.html.erb
<main>
    <p id="notice"></p>
    
    <div class="container px-5 px-sm-0">
        
        <div class="row">
            <% if @book.errors.any? %>
              <%= @book.errors.count %>件のエラーが発生しました
              <br>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
        </div>
        
        <div class="row">

            <%= render 'userinfo',users:@users,book:@book, user:@user %>
            
            <div class="col-md-8 offset-md-1">
                <h2>Book detail</h2>
                <table class="table">
                    <tbody>
                        <tr>
                            <td>
                            <%= link_to user_path(@books.user) do %>
                               <%= image_tag @books.user.get_profile_image(100,100) %><br>
                               <p><%= @books.user.name %></p>
                            </td>
                            <% end %>
                            
                            <td>
                                
                                <%= link_to book_path(@books) do %>
                                    <%= @books.title %>
                                <% end %>
                                
                            </td>
                            
                            <td>
                                <%= @books.body %>
                            </td>
                            <td>
                                <% if @books.user == current_user %>
                                    <%= link_to 'Edit' , edit_book_path(@books) %>
                                
                                <% end %>
                            </td>
                            
                            <td>
                                <% if @books.user == current_user %>
                                    <%= link_to "Destroy", book_path(@books), method: :delete %>
                                <% end %>
                                
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
</main>

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
        <div class="row">
            <h1 class="px-3 mx-auto">
                Welcome to 
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>!
            </h1>
        </div>
    </div>
    
</main>

app/views/homes/top.html.erb
<main>

    <p id="notice"></p>
    <div class="container">
        <div class="row">
            <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                <h1>
                    welcome to 
                    
                    <strong><i class="fas fa-book"></i>Bookers!!</strong>
                </h1>
                
                <p>
                    In
                    
                    <strong><i class="fas fa-book"></i>Bookers</strong>,
                </p>
                <p>you can share and exchange your opinions , inpressions , and emotions</p>
                <p> about various books!</p>
                <div class="btn-wrapper col-10 mx-auto">
                    <div class="row">
                        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                    </div>
                    <div class="row">
                        <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/b68e52c3a0.js" crossorigin="anonymous"></script>

    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <style>
        li {
          padding-left: 13px;
        }
        
        a.fa-home{
          color: black;
          text-decoration: none;
        }
        
        .row {
            display: flex;
            flex-wrap: wrap;
            margin-right: -15px;
            margin-left: -15px;
        }
      </style>
  </head>
  <body>
    
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                
                  <li>
                    <i class="fas fa-home", style="color: white;"></i>
                    <%= link_to "Home", user_path(current_user.id) %>
                  
                  </li>
                
                  <li>
                    <i class="fas fa-users", style="color: white;"></i>
                    <%= link_to "Users ", users_path %>
                  </li>
                  
                  <li>
                    <i class="fas fa-book-open", style="color: white;"></i>
                    <%= link_to "Books ", books_path %>
                  </li>
                  
                  <li>
                    <i class="fas fa-sign-out-alt", style="color: white;"></i>
                    <%= link_to "Log out ", destroy_user_session_path, method: :delete %>
                  </li>
                  
                  <!--ログインしていない場合-->
                <% else %>
                  <li>
                    <i class="fas fa-home", style="color: white;"></i>
                    <%= link_to "Home", root_path %>
                  </li>

                  <li>
                    <i class="fas fa-link", style="color: white;"></i>
                    <%= link_to "About ", home_about_path %>
                  </li>
                
                  <li>
                    <i class="fas fa-user-plus", style="color: white;"></i>
                    <%= link_to "Sign up ", new_user_registration_path %>
                  </li>
                  <li>
                    <i class="fas fa-sign-in-alt", style="color: white;"></i>
                    <%= link_to "Log in ", new_user_session_path %>
                  </li>
              <% end %>
            </ul>
          </div>
          
        </div>
      </nav>
    </header>

<!--フラッシュメッセージ-->
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    
    <div class="container content">
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>

app/views/users/edit.html.erb
<main>
    <p id="notice"></p>
    
    <div class="container">
        
        <div class="row">
            <% if @user.errors.any? %>
              <%= @user.errors.count %>件のエラーが発生しました
              <br>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
        </div>
        
        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
                <h2>User info</h2>
                <%= form_with model: @user do |f| %>
                <div class="form-group">
                    <label for="user_name">Name</label><br>
                    <%= f.text_field :name %>
                </div>
                
                <div class="form-group">
                    <%= f.file_field :profile_image, accept: "image/*" %>

                </div>
                <div class="form-group">
                    <label for="user_introduction">Introduction</label><br>
                    <%= f.text_area :introduction %>
                </div>
                <div class="form-group">
                <%= f.submit 'Update User' %>

                </div>
                <% end %>
            </div>
        </div>
        
    </div>
</main>

app/views/users/index.html.erb
<main>
    <p id="notice"></p>
    
    <div class="container px-5 px-sm-0">
        <div class="row" >
            
            <%= render 'books/userinfo',users:@users,book:@book, user:@user%>

            <div class="col-md-8 offset-md-1">
                <h2>Users</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th>image</th>
                            <th>name</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                    <tbody>
                        
                         <% @user.each do |user| %>
                        <tr>
                            <td>
                                <%= image_tag user.get_profile_image(100,100) %>
                            </td>
                            <td>
                                <%= user.name %>     
                            </td>
                            <td>
                                <%= link_to 'Show', user_path(user) %>
                            </td>
                        </tr>
                        <% end %>
                        
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>
</main>

app/views/users/show.html.erb
<main>
    <p id="notice"></p>
    
    <div class="container px-5 px-sm-0">
        <div class="row" >
             <%= render 'books/userinfo',users:@users,book:@book %>
             <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <% @books.each do |book| %>
                        <tr>
                            <td>
                                <%= link_to user_path(book.user.id) do %>
                                    <%= image_tag book.user.get_profile_image(100,100) %>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to book_path(book.id) do %>
                                    <%= book.title %>
                                <% end %>
                            </td>
                            <td><%= book.body %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
             </div>
        </div>
    </div>
</main>